### ISSUE TITLE
bci_toolbox

### ISSUE THREAD

**Issue by kazila1** [okbalefthanded/bci_toolbox#12]
Hello, okbalefthanded
I ran your program with this error

Index beyond matrix dimension.
error dataio_create_epochs_SM_SanDiego (line 77)
subject_path = [set_path '' dataSetFiles{subj}];

I downloaded your data, too
Is the path wrong? thanks @okbalefthanded

**Comment by okbalefthanded** [comment]
This error means that the dataSetFiles cell is empty. either the directory is not found or it's has no files.
to solve this issue try this:
- create the datasets folder in the toolbox home folder.
- create a new folder with the name "ssvep_sandiego" in the datasets folder and copy the dataset files in it.
- run the setup script from the toolbox home folder.
