### ISSUE TITLE
Index beyond matrix dimension

### ISSUE THREAD

**Issue by gdddara** [okbalefthanded/bci_toolbox#16]
I ran your program with this error
Index beyond matrix dimension.
error dataio_create_epochs_SM_SanDiego (line 77)
subject_path = [set_path '' dataSetFiles{subj}];
and my  dataSetFiles cell is not empty.

**Comment by okbalefthanded** [comment]
@gdddara what does dataSetFiles cell contains ?

**Comment by gdddara** [comment]
> @gdddara what does dataSetFiles cell contains ?

include epochs-ssvep_sandiego-SM （but the SM is empty）and sandiego_ssvep（the sandiego_ssvep include the data（like s1.mat））

**Comment by okbalefthanded** [comment]
A correct subject_path should be like this:"
_"datasets\ssvep_sandiego\s1.mat"_
Make sure that the 'dataset' folder is created in the toolbox folder and the san diego dataset's folder is 'dataset/ssvep_sandiego'. keep the current folder in MATLAB at the toolbox folder.

**Comment by gdddara** [comment]
> A correct subject_path should be like this:"
> _"datasets\ssvep_sandiego\s1.mat"_
> Make sure that the 'dataset' folder is created in the toolbox folder and the san diego dataset's folder is 'dataset/ssvep_sandiego'. keep the current folder in MATLAB at the toolbox folder.

is datasets\ssvep_sandiego\s1.mat or datasets\epochs\ssvep_sandiego\s1.mat ?

**Comment by okbalefthanded** [comment]
it's 'datasets\ssvep_sandiego\s1.mat', after transforming raw data to the toolbox data format the data will be saved in 'datasets\epochs\ssvep_sandiego\SM\S01trainEEG.mat' (for subject 1 etc.).

**Comment by gdddara** [comment]
> it's 'datasets\ssvep_sandiego\s1.mat', after transforming raw data to the toolbox data format the data will be saved in 'datasets\epochs\ssvep_sandiego\SM\S01trainEEG.mat' (for subject 1 etc.).

i try.it's ok .thank you so much

**Comment by gdddara** [comment]
> it's 'datasets\ssvep_sandiego\s1.mat', after transforming raw data to the toolbox data format the data will be saved in 'datasets\epochs\ssvep_sandiego\SM\S01trainEEG.mat' (for subject 1 etc.).

if i want to use PBCCA，what should i do？

**Comment by okbalefthanded** [comment]
> > it's 'datasets\ssvep_sandiego\s1.mat', after transforming raw data to the toolbox data format the data will be saved in 'datasets\epochs\ssvep_sandiego\SM\S01trainEEG.mat' (for subject 1 etc.).
> 
> if i want to use PBCCA，what should i do？

See define_approach_SSVEP.m

**Comment by gdddara** [comment]
> > > it's 'datasets\ssvep_sandiego\s1.mat', after transforming raw data to the toolbox data format the data will be saved in 'datasets\epochs\ssvep_sandiego\SM\S01trainEEG.mat' (for subject 1 etc.).
> > 
> > 
> > if i want to use PBCCA，what should i do？
> 
> See define_approach_SSVEP.m

ok，i want to know if i only load one data（like s1.mat）that calculate “average accuracy“，is the Average accuracy means s1.mat ‘s accuracy？
