### ISSUE TITLE
Degrees of obligatory agreement.

### ISSUE THREAD

**Issue by gdddara** [okbalefthanded/bci_toolbox#17]
i have  another question is that i change to use PBCCA,that will be a error ：
Degrees of obligatory agreement. 
ml_trainFBCCA (line 27)
        model.fbCoefs = (1:alg.options.nrFbs).^(-alg.options.a)+alg.options.b;

**Comment by okbalefthanded** [comment]
@gdddara what values did you use?

**Comment by gdddara** [comment]
> @gdddara what values did you use?

do you means the PBCCA values？is as the same as yours.i do not change.just move the %

**Comment by okbalefthanded** [comment]
@gdddara just change the variables from a vector to a single value and it'll work.

**Comment by gdddara** [comment]
> @gdddara just change the variables from a vector to a single value and it'll work.

i‘m so sorry that i don't understand，do you means change this？：
%% FBCCA
 approach.classifier.learner = 'FBCCA';
 approach.classifier.options.harmonics = 5;
 approach.classifier.options.nrFbs = 5;
 approach.classifier.options.a = [0, 2.5];
 approach.classifier.options.b = [0, 1.5];

**Comment by okbalefthanded** [comment]
@gdddara 
approach.classifier.options.a = 2.5;
approach.classifier.options.b = 1.5;

**Comment by gdddara** [comment]
> @gdddara
> approach.classifier.options.a = 2.5;
> approach.classifier.options.b = 1.5;

i change and run，it still have error：
Quotationless missing letter 'mode'.
Delivery ml_trainFBCCA (line 37)
     if (strcmp (alg.options.mode, 'sync') && ~ isempty (idle_ind))

**Comment by okbalefthanded** [comment]
@gdddara add this line : 
approach.classifier.options.mode = 'sync';

**Comment by gdddara** [comment]
> approach.classifier.options.mode = 'sync';

i know.i add this.but still have the same error

**Comment by okbalefthanded** [comment]
@gdddara there was an error in ml_trainFBCCA, it's fixed now. download the latest version or use git to update the toolbox.

**Comment by gdddara** [comment]
> @gdddara there was an error in ml_trainFBCCA, it's fixed now. download the latest version or use git to update the toolbox.

it‘s ok.yesterday i ask you a question is that i want to know if i only load one data（like s1.mat）that calculate “average accuracy“，is the Average accuracy means s1.mat ‘s accuracy？ if i only load two data（like s1.mat and s2.mat ）that calculate “average accuracy“，is the Average accuracy means the average about s1.mat ‘s accuracy plus the s2.mat‘s ’ accuracy？

**Comment by okbalefthanded** [comment]
@gdddara the run_analysis_SSVEP_eval_Single evaluates the whole set, so the average accuracy is calculated on all subjects. you can write a custom function that evaluates a specified number of subjects.

**Comment by gdddara** [comment]
> the run_analysis_SSVEP_eval_Single evaluates the whole set, so the average accuracy is calculated on all subjects. you can write a custom function that evaluates a specified number of subjects.

ok，thank you so much
