### ISSUE TITLE
 FBCCA average accuracy 

### ISSUE THREAD

**Issue by gdddara** [okbalefthanded/bci_toolbox#19]
I use the FBCCA and CCA to calculate the average accuracy.but the FBCCA's average accuracy is 84.the CCA‘s average accuracy  is 92.5.it's something wrong.the FBCCA's average accuracy should be higher than CCA.

**Comment by okbalefthanded** [comment]
@gdddara The FBCCA method relies on the selection of suitable values for its parameters, those values can be selected manually or through cross-validation grid search.
Read the research paper that introduced the method, the current implementation uses the same code:
ftp://sccn.ucsd.edu/pub/ssvep_benchmark_dataset/FBCCA_JNE15.pdf
