### ISSUE TITLE
Is there any python version

### ISSUE THREAD

**Issue by PatchouliJY** [okbalefthanded/bci_toolbox#21]
Recently I read this thesis and want to understand it well, and then I found this toolbox, but my matlab is not very good, I want to ask if there is a python version that can help me learn it more, thank you very much.

**Comment by okbalefthanded** [comment]
We made the toolbox simple and accessible for both beginners and experts, nevertheless I'm not aware of a python toolbox with the same simplicity.
I can suggest two packages one for general EEG processing and the second tailored for BCI benchmarking:
- mne-python for MEG/EEG processing : https://github.com/mne-tools/mne-python
- MOABB for BCI benchmarking: https://github.com/NeuroTechX/moabb
