### ISSUE TITLE
How to transform the format of my own data？

### ISSUE THREAD

**Issue by zhanghaoran2019** [okbalefthanded/bci_toolbox#23]
Hello, I just joined the BCI community. Now we have g-tec and scan devices to collect EEG signals, but the data format is different, so we can't use this toolbox. I want to ask how to convert the data format? thank you very much indeed

**Comment by okbalefthanded** [comment]
Hi,
Make sure that EEG data is saved in any format that can be read in MATLAB i.e. .mat or .csv (or any EEG format with open source libraries such as EDF/GDF), then write a specific dataio function for your data. see the dataio_create_epochs_SM_* in the dataio folder. The function has to convert your EEG into the toolbox epoched format.

**Comment by zhanghaoran2019** [comment]
十分感谢
