### ISSUE TITLE
SSVEP_TSINGHUA

### ISSUE THREAD

**Issue by tahaolan** [okbalefthanded/bci_toolbox#24]
Hello, I want to know how to use dataio_create_epochs_SM_Tsinghua.m. Where should the folder in the code such as Freq_Phase.mat be created?Thank you.

**Comment by okbalefthanded** [comment]
Hi,
Create a folder in the main toolbox folder, next to datatio, evaluation etc.., the datasets folder should look like this:
```
datasets 
│
└───ssvep_tsinghua_jfpm
│   │   S1.mat
│   │   S2.mat
│   │
└───another_dataset
    │   s1.mat
    │   s2.mat
```
So at the end the toolbox folder tree will look like this:
```
bci_toolbox/
|___dataio
|___datasets
|___evaluation
|___machine_learning
|___...
```

**Comment by tahaolan** [comment]
Thank you, I also want to know what values ​​should be set for epoch_length and filter_band

**Comment by okbalefthanded** [comment]
both are vectors of 2 elements, epoch_length can be any length between 0 and length of samples (6 seconds in Tsinghua). keep in mind that values of epoch_length are of type int and in milliseconds, as for filter band values should cover the stimulation frequencies up to their 3rd harmonics.
example:
epoch_length = [0 1000] (epochs of 1 second)
filter_band = [5 60] (frequencies from 5 to 60 hz)

**Comment by tahaolan** [comment]
![mmexport1619841699117](https://user-images.githubusercontent.com/83409467/116770277-0b280600-aa75-11eb-8e85-28b5fad16a95.jpg)

Why is it reported that the index exceeds a part of the range

**Comment by okbalefthanded** [comment]
This error is raised when the dataio_create_epocsh_SM_Tsinghua can't find datafiles. before running any evaluation make sure to run the setup.m script first and to always execute data_create_epochs functions from the bci_toolbox main folder.

**Comment by tahaolan** [comment]
Thank you, I have another question why L1MCCA and ITCCA can't run

**Comment by okbalefthanded** [comment]
ITCCA wasn't running due to an unmerged commit between master and dev branches, you can download the current code it will run well. Unfortunately L1MCCA requires longer debugging which I can't go through, however I advise you to check the authors code that I translated into this toolbox : https://www.mathworks.com/matlabcentral/fileexchange/50876-mlrforssvepbci_demo

**Comment by tahaolan** [comment]
Hello, does this code use 64 channels? If I only want to use Pz, PO5, PO3, POz, PO4, PO6, O1, Oz and O2, what should I do?

**Comment by okbalefthanded** [comment]
There are two possibilities :
1 - select the channels after reading each subject raw file in dataio_create_epochs. or
2 - select the specific channels after reading epoched files in run_analysis function.

**Comment by whiteblack1566** [comment]
Hello, I would like to know how to solve this problem
![4CAM$3AM2FWPS5%Z`BSQ9Y0](https://github.com/okbalefthanded/bci_toolbox/assets/137740602/b3d11ac4-62e7-47bb-b7d6-827b5395cfed)

**Comment by okbalefthanded** [comment]
> Hello, I would like to know how to solve this problem ![4CAM$3AM2FWPS5%Z`BSQ9Y0](https://private-user-images.githubusercontent.com/137740602/320385020-b3d11ac4-62e7-47bb-b7d6-827b5395cfed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTE4NzAsIm5iZiI6MTcxMjU5MTU3MCwicGF0aCI6Ii8xMzc3NDA2MDIvMzIwMzg1MDIwLWIzZDExYWM0LTYyZTctNDdiYi1iN2Q2LTgyN2I1Mzk1Y2ZlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQxNTUyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTRiZjE4YTk5ZGMyMDcyN2ZjZTA2YTY4YTlkMWM1NDJjNjFmMzVjNDY1NzBkMzgyOGZlZDVkZGU0YWIwYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b0ulWxmx73Jb0OeJjTnmjRvHTPLEXpfrlzkiRu8G3Qo)

I will look into it
